### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by TimJTi** [linux4sam/u-boot-at91#22]
What am I missing...or not found?

Plenty of search hits on console/command line interaction with u-boot but can't find anything comprehensive or vaguely useful when it comes to the deep dpwn detail of creating a port for a new board!!

For example...in the board file I want to probe for SPI flash, and simply report the memory size found. 2 days of searching and I can now probe spi and "find" the device; more searching I can see there are some "priv" or maybe "mtb_info" structures that /might/ have the data I need. But no definitive documentation that actually describes this - surely I shouldn't have to be web trawling for this info?

What have I missed?

**Comment by ehristev** [comment]
Hi,
For sure, I can say honestly, that it's not trivial to add a board in U-boot. There is no 'guide' or 'easy' way to do it.
The DENX website ( the company that created and maintains U-boot) , has some information, but not really comprehensive.
The good part is that U-boot is an open source project, so, the best approach would be to identify a commit in the git log that adds a new board. Then you can see what was added and where, and it can serve you as a starting point to add your board.
This is the way I do it when I add a new board, because honestly, out of my head, I wouldn't know where to start from.
Hope this helps !

**Comment by TimJTi** [comment]
I have been helped via my other issue. Thanks for you time :)
